language: objective-c

env:
  global:
    - R_BUILD_ARGS='--no-manual'
    - R_CHECK_ARGS='--no-manual'

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_bioc_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs
after_success:
  - tail -n6 GoogleGenomics.Rcheck/tests/runTests.Rout

notifications:
  email:
    on_success: change
    on_failure: change
