language: r
sudo: false
cache: packages

# For RProtoBuf dependency in Suggests.
addons:
  apt:
    packages:
      - libprotobuf-dev
      - libprotoc-dev

# Package caching only makes sense for the release versions.
r: bioc-release

warnings_are_errors: false
r_build_args:
# Secure auth credentials can not be made available for pull requests.
r_check_args: "$(if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then echo '--no-examples'; fi)"
